// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carService.proto

package grpc.generate;

public interface CancelResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.generate.CancelResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 reservationId = 1;</code>
   */
  int getReservationId();
}
