// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carService.proto

package grpc.generate;

public final class CarService {
  private CarService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_generate_Reservation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_generate_Reservation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_generate_ListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_generate_ListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_generate_ListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_generate_ListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_generate_GetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_generate_GetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_generate_GetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_generate_GetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_generate_AddRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_generate_AddRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_generate_AddResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_generate_AddResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_generate_CancelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_generate_CancelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_generate_CancelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_generate_CancelResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020carService.proto\022\rgrpc.generate\"\234\001\n\013Re" +
      "servation\022\025\n\rreservationId\030\001 \001(\005\022\022\n\npick" +
      "upTime\030\002 \001(\t\022\026\n\016pickupLocation\030\003 \001(\t\022\023\n\013" +
      "dropoffTime\030\004 \001(\t\022\027\n\017dropoffLocation\030\005 \001" +
      "(\t\022\r\n\005brand\030\006 \001(\t\022\r\n\005model\030\007 \001(\t\"\r\n\013List" +
      "Request\"?\n\014ListResponse\022/\n\013reservation\030\001" +
      " \003(\0132\032.grpc.generate.Reservation\"#\n\nGetR" +
      "equest\022\025\n\rreservationId\030\001 \001(\005\">\n\013GetResp" +
      "onse\022/\n\013reservation\030\001 \001(\0132\032.grpc.generat" +
      "e.Reservation\"=\n\nAddRequest\022/\n\013reservati",
      "on\030\001 \001(\0132\032.grpc.generate.Reservation\"$\n\013" +
      "AddResponse\022\025\n\rreservationId\030\001 \001(\005\"&\n\rCa" +
      "ncelRequest\022\025\n\rreservationId\030\001 \001(\005\"\'\n\016Ca" +
      "ncelResponse\022\025\n\rreservationId\030\001 \001(\0052\226\002\n\020" +
      "CarRentalService\022?\n\004list\022\032.grpc.generate" +
      ".ListRequest\032\033.grpc.generate.ListRespons" +
      "e\022<\n\003get\022\031.grpc.generate.GetRequest\032\032.gr" +
      "pc.generate.GetResponse\022<\n\003add\022\031.grpc.ge" +
      "nerate.AddRequest\032\032.grpc.generate.AddRes" +
      "ponse\022E\n\006cancel\022\034.grpc.generate.CancelRe",
      "quest\032\035.grpc.generate.CancelResponseB\002P\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_grpc_generate_Reservation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_generate_Reservation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_generate_Reservation_descriptor,
        new java.lang.String[] { "ReservationId", "PickupTime", "PickupLocation", "DropoffTime", "DropoffLocation", "Brand", "Model", });
    internal_static_grpc_generate_ListRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_generate_ListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_generate_ListRequest_descriptor,
        new java.lang.String[] { });
    internal_static_grpc_generate_ListResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_grpc_generate_ListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_generate_ListResponse_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_grpc_generate_GetRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_grpc_generate_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_generate_GetRequest_descriptor,
        new java.lang.String[] { "ReservationId", });
    internal_static_grpc_generate_GetResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_grpc_generate_GetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_generate_GetResponse_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_grpc_generate_AddRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_grpc_generate_AddRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_generate_AddRequest_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_grpc_generate_AddResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_grpc_generate_AddResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_generate_AddResponse_descriptor,
        new java.lang.String[] { "ReservationId", });
    internal_static_grpc_generate_CancelRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_grpc_generate_CancelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_generate_CancelRequest_descriptor,
        new java.lang.String[] { "ReservationId", });
    internal_static_grpc_generate_CancelResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_grpc_generate_CancelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_generate_CancelResponse_descriptor,
        new java.lang.String[] { "ReservationId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
