// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carService.proto

package grpc.generate;

public interface ListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.generate.ListRequest)
    com.google.protobuf.MessageOrBuilder {
}
