// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: carService.proto

package grpc.generate;

public interface ListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.generate.ListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .grpc.generate.Reservation reservations = 1;</code>
   */
  java.util.List<grpc.generate.Reservation> 
      getReservationsList();
  /**
   * <code>repeated .grpc.generate.Reservation reservations = 1;</code>
   */
  grpc.generate.Reservation getReservations(int index);
  /**
   * <code>repeated .grpc.generate.Reservation reservations = 1;</code>
   */
  int getReservationsCount();
  /**
   * <code>repeated .grpc.generate.Reservation reservations = 1;</code>
   */
  java.util.List<? extends grpc.generate.ReservationOrBuilder> 
      getReservationsOrBuilderList();
  /**
   * <code>repeated .grpc.generate.Reservation reservations = 1;</code>
   */
  grpc.generate.ReservationOrBuilder getReservationsOrBuilder(
      int index);
}
